/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BootcampRouteImport } from './routes/bootcamp'
import { Route as BootcampIndexRouteImport } from './routes/bootcamp/index'
import { Route as BootcampHomeworkDayRouteImport } from './routes/bootcamp/homework.$day'
import { Route as BootcampChallengeDayExerciseRouteImport } from './routes/bootcamp/challenge.$day.$exercise'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BootcampRoute = BootcampRouteImport.update({
  id: '/bootcamp',
  path: '/bootcamp',
  getParentRoute: () => rootRouteImport,
} as any)
const BootcampIndexRoute = BootcampIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BootcampRoute,
} as any)
const BootcampHomeworkDayRoute = BootcampHomeworkDayRouteImport.update({
  id: '/homework/$day',
  path: '/homework/$day',
  getParentRoute: () => BootcampRoute,
} as any)
const BootcampChallengeDayExerciseRoute =
  BootcampChallengeDayExerciseRouteImport.update({
    id: '/challenge/$day/$exercise',
    path: '/challenge/$day/$exercise',
    getParentRoute: () => BootcampRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bootcamp': typeof BootcampRouteWithChildren
  '/bootcamp/': typeof BootcampIndexRoute
  '/bootcamp/homework/$day': typeof BootcampHomeworkDayRoute
  '/bootcamp/challenge/$day/$exercise': typeof BootcampChallengeDayExerciseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bootcamp': typeof BootcampIndexRoute
  '/bootcamp/homework/$day': typeof BootcampHomeworkDayRoute
  '/bootcamp/challenge/$day/$exercise': typeof BootcampChallengeDayExerciseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bootcamp': typeof BootcampRouteWithChildren
  '/bootcamp/': typeof BootcampIndexRoute
  '/bootcamp/homework/$day': typeof BootcampHomeworkDayRoute
  '/bootcamp/challenge/$day/$exercise': typeof BootcampChallengeDayExerciseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bootcamp'
    | '/bootcamp/'
    | '/bootcamp/homework/$day'
    | '/bootcamp/challenge/$day/$exercise'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bootcamp'
    | '/bootcamp/homework/$day'
    | '/bootcamp/challenge/$day/$exercise'
  id:
    | '__root__'
    | '/'
    | '/bootcamp'
    | '/bootcamp/'
    | '/bootcamp/homework/$day'
    | '/bootcamp/challenge/$day/$exercise'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BootcampRoute: typeof BootcampRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bootcamp': {
      id: '/bootcamp'
      path: '/bootcamp'
      fullPath: '/bootcamp'
      preLoaderRoute: typeof BootcampRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bootcamp/': {
      id: '/bootcamp/'
      path: '/'
      fullPath: '/bootcamp/'
      preLoaderRoute: typeof BootcampIndexRouteImport
      parentRoute: typeof BootcampRoute
    }
    '/bootcamp/homework/$day': {
      id: '/bootcamp/homework/$day'
      path: '/homework/$day'
      fullPath: '/bootcamp/homework/$day'
      preLoaderRoute: typeof BootcampHomeworkDayRouteImport
      parentRoute: typeof BootcampRoute
    }
    '/bootcamp/challenge/$day/$exercise': {
      id: '/bootcamp/challenge/$day/$exercise'
      path: '/challenge/$day/$exercise'
      fullPath: '/bootcamp/challenge/$day/$exercise'
      preLoaderRoute: typeof BootcampChallengeDayExerciseRouteImport
      parentRoute: typeof BootcampRoute
    }
  }
}

interface BootcampRouteChildren {
  BootcampIndexRoute: typeof BootcampIndexRoute
  BootcampHomeworkDayRoute: typeof BootcampHomeworkDayRoute
  BootcampChallengeDayExerciseRoute: typeof BootcampChallengeDayExerciseRoute
}

const BootcampRouteChildren: BootcampRouteChildren = {
  BootcampIndexRoute: BootcampIndexRoute,
  BootcampHomeworkDayRoute: BootcampHomeworkDayRoute,
  BootcampChallengeDayExerciseRoute: BootcampChallengeDayExerciseRoute,
}

const BootcampRouteWithChildren = BootcampRoute._addFileChildren(
  BootcampRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BootcampRoute: BootcampRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
